### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by thiagodelgado111** [orbitdb/orbitdb#445]
## TODO

- [ ] Move manifest related functions to its own space
- [ ] Move Cache handling to the Store
- [ ] Add static "factory" method to create an orbit instance
  - [ ]  Make it async and check if ipfs is ready, throw otherwise
- [ ] After the Store refactoring is done, move it to orbit-db package and inject it into other stores (orbitdb/orbit-db-store#31)

**Comment by aphelionz** [comment]
@thiagodelgado111 I'd love to revisit this at some point with you and the Colony team! Leaving open

**Comment by haadcode** [comment]
Closing as obsolete. A lot of refactoring was done for v1.0.0.
